provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Models/ErrorViewModel.cs
namespace MvcClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClient.Models
{
    public class TaskViewModel
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string Description { get; set; }
        public bool IsFinished { get; set; }
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Controllers/AccountController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using IdentityModel.Client;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System;
using System.Net;
using System.Security.Claims;

namespace MvcClient.Controllers
{
    public class AccountController : Controller
    {
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            if (!Url.IsLocalUrl(returnUrl)) returnUrl = "/";

            var props = new AuthenticationProperties
            {
                RedirectUri = returnUrl
            };

            return Challenge(props, "oidc");
        }

        [Authorize]
        public IActionResult Secure()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> GetApiClaims()
        {
            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            var client = new HttpClient();
            client.SetBearerToken(accessToken);
            var response = await client.GetAsync("http://localhost:3000/identity").ConfigureAwait(false);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                ViewBag.Json = JArray.Parse(content).ToString();
                return View();
            }

            if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("Denied");
            }

            throw new Exception($"Problema ao acessar a API: {response.ReasonPhrase}");
        }

        [Authorize]
        public async Task<IActionResult> GetUserInfo()
        {
            var discoverClient = new DiscoveryClient("https://localhost:44373/");
            var metaDataResponse = await discoverClient.GetAsync();

            var userInfoClient = new UserInfoClient(metaDataResponse.UserInfoEndpoint);

            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            var response = await userInfoClient.GetAsync(accessToken);

            if (response.IsError)
                throw new Exception("Problem accessing the UserInfo endpoint", response.Exception);

            return View(response.Claims);
        }

        public IActionResult Denied(string returnUrl = null)
        {
            return View();
        }

        public async Task Logout()
        {
            // get the metadata
            var discoveryClient = new DiscoveryClient("https://localhost:44373/");
            var metaDataResponse = await discoveryClient.GetAsync();

            // create a TokenRevocationClient
            var revocationClient = new TokenRevocationClient(metaDataResponse.RevocationEndpoint, "taskmvc", "secret");

            // get the access token to revoke 
            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            if (!string.IsNullOrWhiteSpace(accessToken))
            {
                var revokeAccessTokenResponse = await revocationClient.RevokeAccessTokenAsync(accessToken);

                if (revokeAccessTokenResponse.IsError)
                {
                    throw new Exception("Problem encountered while revoking the access token.", revokeAccessTokenResponse.Exception);
                }
            }

            // revoke the refresh token as well
            var refreshToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken);

            if (!string.IsNullOrWhiteSpace(refreshToken))
            {
                var revokeRefreshTokenResponse = await revocationClient.RevokeRefreshTokenAsync(refreshToken);

                if (revokeRefreshTokenResponse.IsError)
                {
                    throw new Exception("Problem encountered while revoking the refresh token.", revokeRefreshTokenResponse.Exception);
                }
            }

            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcClient.Models;

namespace MvcClient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Controllers/PayAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcClient.Controllers
{
    public class PayAreaController : Controller
    {
        [Authorize(Policy = "CanAccessPayArea")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using MvcClient.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using MvcClient.Services;

namespace MvcClient.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly IResourcesHttpClient _resourcesHttpClient;

        public TaskController(IResourcesHttpClient resourcesHttpClient)
        {
            _resourcesHttpClient = resourcesHttpClient;
        }

        public async Task<IActionResult> MyTasks()
        {
            var client = await _resourcesHttpClient.GetClient();
            var response = await client.GetAsync("http://localhost:3000/tasks").ConfigureAwait(false);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                var tasksList = JsonConvert.DeserializeObject<List<TaskViewModel>>(content);
                return View(tasksList);
            }

            if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("Denied", "Account");
            }

            throw new Exception($"Problema ao acessar a API: {response.ReasonPhrase}");
        }

        [Authorize(Roles = "Subscriber")]
        public async Task<IActionResult> Finish(Guid id)
        {
            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            var client = new HttpClient();
            client.SetBearerToken(accessToken);
            var response = await client.PostAsync($"http://localhost:3000/tasks/finish/{id}", null).ConfigureAwait(false);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("MyTasks");
            }

            if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("Denied", "Account");
            }

            throw new Exception($"Problema ao acessar a API: {response.ReasonPhrase}");
        }
    }
}

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Views/PayArea/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Área do Assinante</h2>

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.MvcClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Project.MvcApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Secure">Secure</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="GetApiClaims">Get Claims (API)</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="GetUserInfo">Get User Info (IDP)</a></li>
                    <li><a asp-area="" asp-controller="Task" asp-action="MyTasks">My Tasks</a></li>

                    @if ((await AuthorizationService.AuthorizeAsync(User, "CanAccessPayArea")).Succeeded)
                    {
                        <li><a asp-area="" asp-controller="PayArea" asp-action="Index">Área do Assinante</a></li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">(@(User.Identity.Name)) Logout</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Project.MvcApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

provas-de-conceito/poc-identity-provider/src/Clients/MvcClient/Views/Task/MyTasks.cshtml
@model List<MvcClient.Models.TaskViewModel>

@{
    ViewData["Title"] = "My Tasks";
}

<h2>My Tasks</h2>

@if (TempData["Sucesso"] != null)
{
    <div class="alert">@TempData["Sucesso"]</div>
}

<dl>
    @foreach (var task in Model)
    {
        <dd>
        @if (task.IsFinished)
        {
            <span style="text-decoration:line-through">@task.Description</span>
        }
        else
        {
            @task.Description
        }
        </dd>

        if (!task.IsFinished)
        {
            <dd><a href="~/task/finish/@task.Id">Set Completed</a></dd>
        }
    }
</dl>